# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a86a8e890ad3c0f2579b6e88cc19e78cf42df430bf16a13a8bcf5f2343313e4e3e9d250430d2b74eebec3eec95467df184eecbdee038173c14e91d2eed88c5f

test:
  secret_key_base: 4bdba349b84e0192eed6ff3576ad8e2f21436314316b6fa89d0942a2489e4a1becb099b4adc3c4c998a9256fe51a90a1220c683cf23798c994d939521a52602b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
